Add attack animations
BadassBison/Bokudos pull request #35
Opened 2020-12-30 22:20 UTC by codymaki

## Changes

 - add standing attack animation
 - add jump attack animation
 - updated ninja render to adjust from center of image
 - allow jumping with space bar
 - added mouse click to control attacks

## References

- https://github.com/BadassBison/Bokudos/issues/28
- https://github.com/BadassBison/Bokudos/issues/27

2020-12-31 01:13 UTC, BadassBison requested changes

2020-12-31 01:13 UTC, BadassBison commented on src/objects/game.ts
> +    document.addEventListener('mousedown', (evt: MouseEvent) => this.parseKey(evt.type, true));
Instead of the document, add these eventListeners to the canvas. This will allow for us to click on assets in debug mode with out triggering any actions

2020-12-31 01:13 UTC, BadassBison commented on src/objects/game.ts
> +        this.state.keys.up = pressed;
This just makes me laugh, thanks for cleaning this up

2020-12-31 01:13 UTC, BadassBison commented on src/objects/ninja.ts
> +        State.gameState.position = { x: this.state.position.x - State.gameState.gameUnitDimensions.w / 2, y: this.state.position.y - 5 };
I think we should probably add this logic to a utility method for getting this position. I can see it being useful all over the game

2021-01-05 22:11 UTC, codymaki commented
This PR resolves this: https://github.com/BadassBison/Bokudos/pull/39

2021-01-05 22:11 UTC, closed without merging